name: DStruct Test CI

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: config and install tools
      run: wget https://xmake.io/shget.text -O - | bash
    - name: set build mode
      run: xmake f -m debug
    - name: build examples|test
      run: xmake
    - name: run all test
      run: xmake r

  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: config and install tools
      run: Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
    - name: set build mode
      run: xmake f -m debug
    - name: build examples|test
      run: xmake
    - name: run all test
      run: xmake r